import pygame


PLAYER_TURN_EVENT = pygame.USEREVENT + 1
BOSS_TURN_EVENT = pygame.USEREVENT + 2

BOSS_HITTED = pygame.USEREVENT + 3

BOSS_ACT_EFFECT = pygame.USEREVENT + 4


STOP_HEART_COLOR = (5, 153, 245)
MOVE_HEART_COLOR = (255, 145, 0)
